#!/bin/bash

files="profile bashrc zshrc vimrc gvimrc vim gtkrc-2.0 tmux.conf i3 i3status.conf ncmpcpp mpd"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# clean and backup

if [ -d "$HOME/dotfiles_backup" ]; then
    echo "Backup directory already generated."
else
    mkdir ~/dotfiles_backup
    for file in $files; do
        # move file or directory to backup directory only if it exists
        if [ -f "$HOME/.$file" ] || [ -d "$HOME/.$file" ] || [ -L "$HOME/.$file" ]; then
            mv ~/.$file ~/dotfiles_backup/$file
        fi

        echo "Creating symlink to $DIR/$file...done!"
        # create symlink
        ln -s $DIR/$file ~/.$file
    done
fi
